### ISSUE TITLE
Any plan to merge this upstream?

### ISSUE THREAD

**Issue by miminar** [deejross/python3-pywbem#2]
I'm sure that upstream would be glad to accept python 3 compatibility patches. Could you please propose your changes on [upstream mailing list](pywbem-devel@lists.sourceforge.net)?

**Comment by rosspeoples** [comment]
While a good idea, I think upstream will have an issue with compatibility. They maintain Python compatibility all the way back to at least 2.3, maybe even further than that, while the changes I've made only work in Python 2.6+. Since there are still some Linux distributions out there that are fully supported by their vendors that are running much older versions of Python, I doubt the upstream maintainers would be willing to accept my patches, since that's typically their target market. As an example, RHEL 5 is still fully supported by RedHat with Python 2.4, while RHEL 4 is in extended support until 2017.

If that is a compromise upstream is willing to make, then I'm all for it.

**Comment by rchateauneu** [comment]
"They maintain Python compatibility all the way back to at least 2.3"

Could not make it work with Python 2.5.2, I will check twice.

**Comment by rosspeoples** [comment]
That is interesting. I know that there are code comments specifically mentioning old Python versions, but it is possible that those comments and code blocks were just never removed or updated as newer Python versions became supported.

I emailed the upstream mailing list, per miminar's suggestion, so we'll see what they come back with.

**Comment by rkuska** [comment]
Hi,

do you have any update from upstream?

**Comment by rosspeoples** [comment]
Unfortunately, no. My posting on their mailing list was ignored. 

On Thu, Jun 18, 2015 at 7:52 AM -0700, "Robert Kuska" notifications@github.com wrote:

Hi,

do you have any update from upstream?

**Comment by andy-maier** [comment]
Hi. I'm really sorry for the delay.
I'm happy to integrate the changes in the upstream pywbem.
Andy

**Comment by rosspeoples** [comment]
Hi Andy,

How would you propose about getting changes merged upstream?

Thanks, Ross

**Comment by andy-maier** [comment]
Hi Ross,
I think it is generally possible to have a single source that supports both Python 2.x and 3.x. If needed, there could even be runtime tests for the version.

It is definitely a requirement to maintain compatibility at the client API for Python 2.x code.

As far as the process goes, let me take a look at your changes, and then I can integrate them upstream.

All,
backwards support for Python 2.x exists only for 2.6 and 2.7 (for the pywbem client, not sure for the other subprojects). I recently stumbled across a statement of supporting back to 2.3, but that is not correct.
If anyone has a requirement fir supporting earlier than 2.6, let me know (including why).

Cheers
Andy

**Comment by rchateauneu** [comment]
Hi

At the moment python3-wbem does not need m2crypto, apparently. Which is 
really great because installing it on Windows is extremely painful (for 
example, it does not work with the latest SWIG version: 
https://github.com/swig/swig/issues/344 ).

Would it be also possible for pywbem python2, to use something else than 
m2crypto ?

Thanks

Remi

**Comment by rosspeoples** [comment]
The only issue I see with dropping m2crypto as a dependency for Python 2.x is that the built-in "ssl" module (while introduced in Python 2.6) didn't add the "create_default_context" function, which is used in python3-wbem, until Python 2.7.9. It might be possible to duplicate its functionality in Python 2.6 using the Python 2.7.9 source as shown here: https://github.com/python/cpython/blob/2.7/Lib/ssl.py#L395

This would of course need to be coded and tested before upstream would consider dropping m2crypto, since they need to support Python 2.6 as Andy mentioned earlier.

**Comment by andy-maier** [comment]
Today, we have merged the Python 3 support in the upstream repo, from its python3 development branch into the master branch. It will be part of the upcoming 0.8.0 release.
I did a number of changes on top of what you prepared here, so please if you do any further changes, do it based upon the master branch of the upstream repo.
Thanks for all the good work!

**Comment by rosspeoples** [comment]
Excellent! Thanks for letting me know. Glad I was able to contribute.

**Comment by rchateauneu** [comment]
... Your work is saving my project ...

(rdfmon on sourceforge)

Thanks !

Remi
